### ISSUE TITLE
Implement Crossdock echo behaviors

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc#17]
1. Create a branch called `crossdock-echo-behaviors`.
2. Implement the first 3 echo tests from [crossdock.md](https://github.com/yarpc/yarpc/blob/master/crossdock.md)
3. Run against other langs `crossdock-echo-behaviors` branch.
4. Land, then create commits switching to `master`.

TODO:

- [x] yarpc-go - https://github.com/yarpc/yarpc-go/issues/73
- [x] yarpc-java - https://github.com/yarpc/yarpc-java/issues/61
- [x] yarpc-node - https://github.com/yarpc/yarpc-node/issues/46
- [x] yarpc-python - https://github.com/yarpc/yarpc-python/issues/34

**Comment by breerly** [comment]
@kriskowal I want you to take the lead on this - work with lang leaders to get this out good sir.

**Comment by breerly** [comment]
@kriskowal this is dependent on #18

**Comment by breerly** [comment]
@kriskowal no need to create new tickets, we'll just create PR's for each of the destined repos

**Comment by kriskowal** [comment]
I’ve created `crossdock-echo-behaviors` branch on each repository. This covers http,tchannel and raw,json,thrift.
