### ISSUE TITLE
Handling of unwanted HTTP headers

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc#2]
Currently, the scheme we are using for headers is:

- Application headers get sent and received as-is as HTTP headers.
- YARPC headers use `YARPC-*` names.

Under this scheme, we will end up receiving HTTP headers that users did not actually specify. Things like, `Content-Length`, `Accept-Encoding`, `User-Agent`, etc. How do we want to handle these? Obvious options are:

1. Pass them around anyway.
2. Maintain a blacklist of HTTP headers that are removed when we are removing the `YARPC-*` headers.
3. Prefix application headers with something.

I would rather not do 1 because it's leaking details of the transport to layers that should not know/care about them. I dislike 2 because if at some point after release we decide that some other header should be blacklisted too, we risk breaking people who might be relying on that header's presence. 

CC @yarpc/yarpc

**Comment by breerly** [comment]
This is done 🎉
