### ISSUE TITLE
Application header case sensitivity

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc#3]
Should application header names be case sensitive or insensitive. Given that we're supporting HTTP, sounds like they should be case insensitive. I would like to reach a consensus here and open issues against the language-specific repos.

CC @yarpc/yarpc

**Comment by prashantv** [comment]
+1 for case insensitive header names. Otherwise we'd have to encode the case into the string for HTTP which would make them ugly.

**Comment by abhinav** [comment]
Consensus: case-insensitive headers, especially to support HTTP. Resolving.

**Comment by abhinav** [comment]
Actually, leaving open until we write this down somewhere

**Comment by junchaowu** [comment]
What will be the right behavior if we detect there is the duplicate words ?

**Comment by abhinav** [comment]
As per https://github.com/yarpc/yarpc/blob/master/headers.md,

> An inbound request with duplicate, normalized keys is a bad request and effects a [DecodeHeadersForInboundRequest](errors.md#DecodeHeadersForInboundRequest) error.

> An outbound request with duplicate, normalized keys cannot be sent and effects an [EncodeHeadersForOutboundRequest](errors.md#EncodeHeadersForOutboundRequest) error.

**Comment by breerly** [comment]
@abhinav now that we're normalizing headers, this isn't an issue anymore?

**Comment by abhinav** [comment]
True.
