### ISSUE TITLE
Middleware (interceptors & filters)

### ISSUE THREAD

**Issue by junchaowu** [yarpc/yarpc#44]
I did first prototype on YARPC middleware design. For my current design, I use term “Interceptor”, which will invoke interceptor methods in conjunction with method invocations or lifecycle events on an associated target class. Requests and Responses are mutable by passing through interceptors. I followed the design pattern: "[Intercepting Filter Pattern](http://www.oracle.com/technetwork/java/interceptingfilter-142169.html)" which is widely used in other frameworks like Netty, Jersey, CXF.

YARPC has 4 “channel/path" - inbound request, outbound response, outbound request, inbound response. YARPC also has 2 layers: application layer and transport level.  As a result, one interceptor can be put in to one of the 4*2 places. 
![image](https://cloud.githubusercontent.com/assets/3731781/14054992/2d7b5b4a-f29b-11e5-8d65-9056ae6e0878.png)
By referring to the design of Netty, the intercepting methods for request and response can be put into single interceptor class, therefore this table can be transformed like this:
![image](https://cloud.githubusercontent.com/assets/3731781/14054993/33f26cc0-f29b-11e5-8d3b-3bcb5ba8ff72.png)
It now because 4 possible combinations:

The Intercepter interface will look like this:
```java
public interface Intercepter {
    boolean handle(Request<?> request);

    boolean handle(Response<?> response);
}
```
You will notice the return type of Intercepter is boolean. The boolean value will indicate whether it want to block the next intercepter or not.
This is an logging intercepter example:
```java
public class LogIntercepter extends AbstractPhaseIntercepter {
    private static final Logger logger = LoggerFactory.getLogger(LogIntercepter.class);

    public LogInterceptor() {
        super(Phase.TRANSPORT); // or Phase.Application 
    }

    public boolean handle(Request<?> request) {
        logger.info("Request: {}", request.toString());
        return true;
    }

    public boolean handle(Response<?> response) {
        logger.info("Response: {}", response.toString());
        return true;
    }
}
```
The register method will look like this:
```java
rpc.getIntercepterManager().addClientInterceptor(new LogIntercepter());
rpc.getIntercepterManager().addServerInterceptor(new LogIntercepter());
```
The intercepter execution sequence is based on insertion sequence.

**Comment by junchaowu** [comment]
@yarpc/yarpc

**Comment by abhinav** [comment]
Couple things:

* I would recommend against providing application level interceptors, and instead provide only transport level intercepters. This will discourage users from relying on decoded request bodies and putting application logic inside interceptors.
* Find a better name than interceptor manager.
* Also, it's my understanding that "interceptor" is the correct spelling

**Comment by breerly** [comment]
closing in favor of #57
