### ISSUE TITLE
HTTP/1.1: Application headers must be prefixed with `Rpc-Header-`

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc#55]
For the HTTP/1.1 transport, we should prefix all application headers with `Rpc-Header-` over the wire. These prefixes will be added before writing to the wire, and stripped off before passing off the request to the user.

The primary motivation behind this change is this: HTTP clients will automatically add some standard HTTP headers, including but not limited to `User-Agent` and `Content-Length`. Under the current scheme of exposing all non-Rpc headers to the user, these will end up stomping on or conflicting with user-defined application headers (for example if the user passes a `Content-Length` header which doesn't match the actual length of the HTTP request body).

I propose that we prepend `Rpc-Header-` to all application headers before sending them over the wire, and strip the prefix when reading the headers off the wire. The user experience will not change in any way because users will still get back the headers they wrote.

More concretely, `{"foo": "bar", "content-length": "42"}` should translate to the following over the wire:

    Rpc-Header-Foo: bar
    Rpc-Header-Content-Length: 42

This applies to both, Request and Response headers.

CC @yarpc/yarpc 

-----

Implementation:

- [x] Go (https://github.com/yarpc/yarpc-go/pull/118)
- [x] Python (https://github.com/yarpc/yarpc-python/pull/77)
- [x] Node (https://github.com/yarpc/yarpc-node/pull/70)
- [x] Java (https://github.com/yarpc/yarpc-java/pull/90)

**Comment by breerly** [comment]
I'm onboard - let's make this happen as part of our header crossdock tests 👍

**Comment by blampe** [comment]
So this is separate from "RPC-" headers? That is, "RPC-Header" prefixes application headers for the request?

**Comment by abhinav** [comment]
Yes. `Rpc-*` headers are for YARPC, and `Rpc-Header-*` headers are application headers

**Comment by abhinav** [comment]
Down to the last one: https://github.com/yarpc/yarpc-java/pull/90

**Comment by abhinav** [comment]
All languages now have this functionality. Resolving.

**Comment by breerly** [comment]
💥 🎉
