### ISSUE TITLE
Feature request: ability to apply middleware to 3rd-party requests

### ISSUE THREAD

**Issue by blampe** [yarpc/yarpc#62]
Another one from @nharkins:

Calls to third-party services (think S3, maps, etc.) are similar in a lot of ways to internal RPC calls in that it would be really nice to have things like consistent metrics around them, maybe circuit breaking, etc. It would be nice to be able to apply some middleware (but not all of it -- for example we don't want to send context headers to 3rd parties) to these 3rd-party call sites. Combined with #61 you could use this to simulate 3rd-party outages.

**Comment by breerly** [comment]
Middleware can be applied to all inbound and outbound calls - it's just a matter of implementing transports for these 3rd party APIs to get all of YARPCs functionality.
