### ISSUE TITLE
Explicit notion of Server on the RPC(plane)

### ISSUE THREAD

**Issue by bombela** [yarpc/yarpc#64]
The yarpc library exposes a way to create a library context. Currently called "RPC". This context manages a set of inbound and outbound connections. The context accepts configuration of the different network transports.

This RPC context can instantiate many client channels. On the other hand, this RPC context can expose a single Server.

Instead, let's have the ability to add as many Server as we want per RPC context. A server has a name, and a bunch of methods.

Example: you have a service "sawmill" serving a bunch of logs. The service runs on a 100 machines. Each machine has a Go process with a single RPC context. This RPC context has a registered Server "sawmill". The sawmill server has a method "get_logs". The RPC context has also a second Server "stats", exposing process specific stats about this process.

Because a Server is now decoupled from the RPC context, it is possible to have reusable libraries of servers that can be attached to an RPC context at will.

Note this is similar to the notion of namespacing. Although in this case we have a word and a concept to talk about and manipulate a bag of methods under the same umbrella.

**Comment by breerly** [comment]
We need the service name at the highest level because:

- Handles need to register against a service name for dispatching.
- Clients need the service name to set the `Caller` transport header and for logging/stats/etc...

**Comment by abhinav** [comment]
@bombela It sounds like you're asking to host multiple logical services behind a single service. We sort of already support that for Thrift at least. You can have multiple Thrift services behind a single named service. For example, all TChannel services host their own service (which could be Thrift) plus the Meta Thrift service defined here: https://github.com/uber/tchannel-python/blob/master/tchannel/health/meta.thrift

**Comment by abhinav** [comment]
To clarify: In the context of the RPC object, the name 'service' refers to the name used for routing.

**Comment by bombela** [comment]
@abhinav yes that's what I am asking for, but exposed at the high level.

An RPC plane has a single logical inbound to my process. Behind this inbound endpoint, I want more than one service.

I can namespace stuff in Thrift (multiple service definition) or by hand "foo.bar.get", but this is not a first class notion of exposing many services.

In short, I want the same notion of multiple thrift services, but at the level of yarpc. And yes, it then means if you have two services in your thrift idl, you should have two Server objects in your code.

**Comment by blampe** [comment]
What would the current API vs. an API like what you're describing look like?

**Comment by bombela** [comment]
Using yarpc-go as an example.

Looks like there is the notion of service there: https://github.com/yarpc/yarpc-go/blob/8934bfbd98630639a03c7ba0b4abbfbcef15e660/transport/register.go#L32

Not used by the thrift encoding: 
https://github.com/yarpc/yarpc-go/blob/8934bfbd98630639a03c7ba0b4abbfbcef15e660/encoding/thrift/register.go#L66

Which does its own namespacing: https://github.com/yarpc/yarpc-go/blob/8934bfbd98630639a03c7ba0b4abbfbcef15e660/encoding/thrift/procedure.go#L30

So really, its already fairly close to what I am asking, and it looks like we can build some sort of API to manipulate services specific configurations and details around that (thanks @abhinav for the pointers).

**Comment by breerly** [comment]
This is solved by the Dispatcher concept now.
